//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedWp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NedWp.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue.
        /// </summary>
        public static string ADDTOQUEUE {
            get {
                return ResourceManager.GetString("ADDTOQUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No help available for this screen.
        /// </summary>
        public static string App_OpeningHelpErrorUnknowScreen {
            get {
                return ResourceManager.GetString("App_OpeningHelpErrorUnknowScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ARE_YOU_SURE {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string BAD_LOGIN {
            get {
                return ResourceManager.GetString("BAD_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogues: {0}.
        /// </summary>
        public static string CATALOGS {
            get {
                return ResourceManager.GetString("CATALOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string CataloguePage_RefreshButton {
            get {
                return ResourceManager.GetString("CataloguePage_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: {0}.
        /// </summary>
        public static string CATEGORIES {
            get {
                return ResourceManager.GetString("CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check for updates.
        /// </summary>
        public static string CHECK_FOR_UPDATE {
            get {
                return ResourceManager.GetString("CHECK_FOR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string CHOOSE_LANGUAGE {
            get {
                return ResourceManager.GetString("CHOOSE_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string CONNECTING {
            get {
                return ResourceManager.GetString("CONNECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo library id &apos;khan&apos;.
        /// </summary>
        public static string DEMOLIBID {
            get {
                return ResourceManager.GetString("DEMOLIBID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For demo please use login and password &apos;guest&apos;.
        /// </summary>
        public static string DemoLoginDetails {
            get {
                return ResourceManager.GetString("DemoLoginDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For demo please use:.
        /// </summary>
        public static string DEMOURL {
            get {
                return ResourceManager.GetString("DEMOURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics uploaded successfully.
        /// </summary>
        public static string DLM_SUCCESSFULLUPLOAD {
            get {
                return ResourceManager.GetString("DLM_SUCCESSFULLUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download all.
        /// </summary>
        public static string DOWNLOAD_ALL {
            get {
                return ResourceManager.GetString("DOWNLOAD_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download now.
        /// </summary>
        public static string DOWNLOAD_NOW {
            get {
                return ResourceManager.GetString("DOWNLOAD_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added to download queue.
        /// </summary>
        public static string DownloadCommand_AddedToDownload {
            get {
                return ResourceManager.GetString("DownloadCommand_AddedToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already downloaded.
        /// </summary>
        public static string DownloadCommand_AlreadyDownloaded {
            get {
                return ResourceManager.GetString("DownloadCommand_AlreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} downloading started.
        /// </summary>
        public static string DownloadCommand_DownloadingStarted {
            get {
                return ResourceManager.GetString("DownloadCommand_DownloadingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string DownloadCommand_Item {
            get {
                return ResourceManager.GetString("DownloadCommand_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter NED server address.
        /// </summary>
        public static string ENTER_SERVER_ADDRESS {
            get {
                return ResourceManager.GetString("ENTER_SERVER_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect with server. Make sure your network connection is working and try again..
        /// </summary>
        public static string Error_Connection {
            get {
                return ResourceManager.GetString("Error_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password cannot be empty.
        /// </summary>
        public static string Error_EmptyUsernameOrPassword {
            get {
                return ResourceManager.GetString("Error_EmptyUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library was deleted from server.
        /// </summary>
        public static string Error_LibraryDeletedFromServer {
            get {
                return ResourceManager.GetString("Error_LibraryDeletedFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library id cannot be empty..
        /// </summary>
        public static string Error_LibraryIdEmpty {
            get {
                return ResourceManager.GetString("Error_LibraryIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error has occured..
        /// </summary>
        public static string Error_Unexpected {
            get {
                return ResourceManager.GetString("Error_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to factory reset.
        /// </summary>
        public static string FACTORY_SETTINGS {
            get {
                return ResourceManager.GetString("FACTORY_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media items enqueued for download: {0}.
        /// </summary>
        public static string ITEM_ADDED_TO_QUEUE {
            get {
                return ResourceManager.GetString("ITEM_ADDED_TO_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to libraries.
        /// </summary>
        public static string LIBRARIES {
            get {
                return ResourceManager.GetString("LIBRARIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library is already added.
        /// </summary>
        public static string LIBRARY_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("LIBRARY_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New library ID.
        /// </summary>
        public static string LIBRARY_ID {
            get {
                return ResourceManager.GetString("LIBRARY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to library manager.
        /// </summary>
        public static string LIBRARY_MANAGER {
            get {
                return ResourceManager.GetString("LIBRARY_MANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library doesn&apos;t exist..
        /// </summary>
        public static string LIBRARY_NOT_EXISTS {
            get {
                return ResourceManager.GetString("LIBRARY_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to remove unknown item type.
        /// </summary>
        public static string LibraryModel_RemovingUnknowTypeError {
            get {
                return ResourceManager.GetString("LibraryModel_RemovingUnknowTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library is no longer available.
        /// </summary>
        public static string LibraryUnavailableAfterFailedUpdate {
            get {
                return ResourceManager.GetString("LibraryUnavailableAfterFailedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string MainPage_Add {
            get {
                return ResourceManager.GetString("MainPage_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding library.
        /// </summary>
        public static string MainPage_AddingLibrary {
            get {
                return ResourceManager.GetString("MainPage_AddingLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will be closed..
        /// </summary>
        public static string MainPage_ClosingApplicationMessage {
            get {
                return ResourceManager.GetString("MainPage_ClosingApplicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string MainPage_Downloading {
            get {
                return ResourceManager.GetString("MainPage_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading library.
        /// </summary>
        public static string MainPage_DownloadingLib {
            get {
                return ResourceManager.GetString("MainPage_DownloadingLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string MainPage_NewVersionAvailableHeader {
            get {
                return ResourceManager.GetString("MainPage_NewVersionAvailableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace current version of this library with new version? (NOTE: all downloaded media will be deleted).
        /// </summary>
        public static string MainPage_NewVersionAvailableMessage {
            get {
                return ResourceManager.GetString("MainPage_NewVersionAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No downloads pending.
        ///
        ///You can select media items to download while browsing the Library..
        /// </summary>
        public static string MainPage_NoDownloadPending {
            get {
                return ResourceManager.GetString("MainPage_NoDownloadPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No libraries to display. 
        ///
        ///Use Library Manager to download libraries and add them here..
        /// </summary>
        public static string MainPage_NoLibrariesToDisplay {
            get {
                return ResourceManager.GetString("MainPage_NoLibrariesToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No libraries to display.
        ///
        ///Type in the library ID and click &apos;Add&apos; to check if library is available..
        /// </summary>
        public static string MainPage_NoLibrariesToDisplayTypeID {
            get {
                return ResourceManager.GetString("MainPage_NoLibrariesToDisplayTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string MainPage_OK {
            get {
                return ResourceManager.GetString("MainPage_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string MainPage_Paused {
            get {
                return ResourceManager.GetString("MainPage_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        public static string MainPage_Queued {
            get {
                return ResourceManager.GetString("MainPage_Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string MainPage_Stopped {
            get {
                return ResourceManager.GetString("MainPage_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update not necessary.
        /// </summary>
        public static string MainPage_UpdateNotNecessaryHeader {
            get {
                return ResourceManager.GetString("MainPage_UpdateNotNecessaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the current version of this library. Do you want to download it anyway? (NOTE: all downloaded media will be deleted).
        /// </summary>
        public static string MainPage_UpdateNotNecessaryMessage {
            get {
                return ResourceManager.GetString("MainPage_UpdateNotNecessaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views: {0}.
        /// </summary>
        public static string MainPage_ViewsCount {
            get {
                return ResourceManager.GetString("MainPage_ViewsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media items: {0} (downloaded: {1}, on server: {2} ).
        /// </summary>
        public static string MEDIA_ITEMS {
            get {
                return ResourceManager.GetString("MEDIA_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are really sorry but we are unable to open this media item..
        /// </summary>
        public static string MediaItemViewerPage_CanNotOpenItem {
            get {
                return ResourceManager.GetString("MediaItemViewerPage_CanNotOpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture.
        /// </summary>
        public static string MediaItemViewerPage_Title {
            get {
                return ResourceManager.GetString("MediaItemViewerPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are really sorry but we are unable to show you this document..
        /// </summary>
        public static string MediaItemViewerPage_UnableToOpenDocument {
            get {
                return ResourceManager.GetString("MediaItemViewerPage_UnableToOpenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string MID_BACK_COMMAND {
            get {
                return ResourceManager.GetString("MID_BACK_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string MID_DEFAULTMOTD {
            get {
                return ResourceManager.GetString("MID_DEFAULTMOTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic downloads.
        /// </summary>
        public static string MID_DOWNLOAD_STATE_SETTINGS {
            get {
                return ResourceManager.GetString("MID_DOWNLOAD_STATE_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.
        /// </summary>
        public static string MID_DOWNLOADS {
            get {
                return ResourceManager.GetString("MID_DOWNLOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string MID_OFF_SETTINGS {
            get {
                return ResourceManager.GetString("MID_OFF_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string MID_ON_SETTINGS {
            get {
                return ResourceManager.GetString("MID_ON_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MID_OPTIONS_COMMAND {
            get {
                return ResourceManager.GetString("MID_OPTIONS_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MID_SEARCH_COMMAND {
            get {
                return ResourceManager.GetString("MID_SEARCH_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MID_SEARCH_TITLE {
            get {
                return ResourceManager.GetString("MID_SEARCH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MID_SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("MID_SETTINGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics.
        /// </summary>
        public static string MID_STATISTICS_COMMAND {
            get {
                return ResourceManager.GetString("MID_STATISTICS_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOKIA EDUCATION DELIVERY.
        /// </summary>
        public static string MID_TITLE {
            get {
                return ResourceManager.GetString("MID_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string MID_UPLOAD_COMMAND {
            get {
                return ResourceManager.GetString("MID_UPLOAD_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help not available.
        /// </summary>
        public static string MISSING_HELP {
            get {
                return ResourceManager.GetString("MISSING_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application restart is required to apply the changes. Do you want to close the application now?.
        /// </summary>
        public static string MSG_RESTART_NEEDED {
            get {
                return ResourceManager.GetString("MSG_RESTART_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application restart is required to apply the changes..
        /// </summary>
        public static string MSG_RESTART_NEEDED2 {
            get {
                return ResourceManager.GetString("MSG_RESTART_NEEDED2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid NED server address.
        /// </summary>
        public static string NEDSERVICENOTPRESENT {
            get {
                return ResourceManager.GetString("NEDSERVICENOTPRESENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description available.
        /// </summary>
        public static string NO_DETAILS {
            get {
                return ResourceManager.GetString("NO_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No links are attached to this media item..
        /// </summary>
        public static string NO_LINKS {
            get {
                return ResourceManager.GetString("NO_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating library.
        /// </summary>
        public static string ProgressOverlay_UpdatingLibrary {
            get {
                return ResourceManager.GetString("ProgressOverlay_UpdatingLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user will be logged out..
        /// </summary>
        public static string QUESTION_LOGOUT_USER {
            get {
                return ResourceManager.GetString("QUESTION_LOGOUT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library will be removed from the device..
        /// </summary>
        public static string QUESTION_REMOVE_LIBRARY {
            get {
                return ResourceManager.GetString("QUESTION_REMOVE_LIBRARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me!.
        /// </summary>
        public static string REMEMBERME {
            get {
                return ResourceManager.GetString("REMEMBERME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove user.
        /// </summary>
        public static string REMOVE_USER {
            get {
                return ResourceManager.GetString("REMOVE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results to display.
        ///
        ///Enter a valid keyword and press search button..
        /// </summary>
        public static string SearchPage_NoResultsToDisplay {
            get {
                return ResourceManager.GetString("SearchPage_NoResultsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server wizard.
        /// </summary>
        public static string SERVER_WIZARD {
            get {
                return ResourceManager.GetString("SERVER_WIZARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing data.
        /// </summary>
        public static string SettingsPage_ClearingData {
            get {
                return ResourceManager.GetString("SettingsPage_ClearingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data will be removed..
        /// </summary>
        public static string SettingsPage_FactoryResetInfoMessage {
            get {
                return ResourceManager.GetString("SettingsPage_FactoryResetInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out.
        /// </summary>
        public static string SettingsPage_LoggingOut {
            get {
                return ResourceManager.GetString("SettingsPage_LoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing user.
        /// </summary>
        public static string SettingsPage_RemovingUser {
            get {
                return ResourceManager.GetString("SettingsPage_RemovingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All user data will be removed..
        /// </summary>
        public static string SettingsPage_UsersRemovedInfoMessage {
            get {
                return ResourceManager.GetString("SettingsPage_UsersRemovedInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string SHOW_DETAILS {
            get {
                return ResourceManager.GetString("SHOW_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Libraries.
        /// </summary>
        public static string SHOW_LIBRARY {
            get {
                return ResourceManager.GetString("SHOW_LIBRARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to links.
        /// </summary>
        public static string SHOW_LINKS {
            get {
                return ResourceManager.GetString("SHOW_LINKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media items opened since last statistics upload to server.
        ///
        ///Statistics are uploaded automatically when &apos;Automatic upload&apos; turned on in settings..
        /// </summary>
        public static string StatisticPage_NoMediaOpened {
            get {
                return ResourceManager.GetString("StatisticPage_NoMediaOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no statistics to upload.
        /// </summary>
        public static string StatisticPage_NoStatisticToUpload {
            get {
                return ResourceManager.GetString("StatisticPage_NoStatisticToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started uploading statistics to server.
        /// </summary>
        public static string StatisticPage_StartedUploading {
            get {
                return ResourceManager.GetString("StatisticPage_StartedUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics.
        /// </summary>
        public static string StatisticPage_Title {
            get {
                return ResourceManager.GetString("StatisticPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload statistics.
        /// </summary>
        public static string StatisticPage_UploadFiles {
            get {
                return ResourceManager.GetString("StatisticPage_UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic statistics upload.
        /// </summary>
        public static string STATISTICS_SENDING_MODE {
            get {
                return ResourceManager.GetString("STATISTICS_SENDING_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout user.
        /// </summary>
        public static string SWITCH_USER {
            get {
                return ResourceManager.GetString("SWITCH_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user login.
        /// </summary>
        public static string USER_AUTHENTICATION {
            get {
                return ResourceManager.GetString("USER_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string USER_NAME {
            get {
                return ResourceManager.GetString("USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.{1}.{2}.
        /// </summary>
        public static string VERSION {
            get {
                return ResourceManager.GetString("VERSION", resourceCulture);
            }
        }
    }
}
