//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NedWp.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NedWp.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOKIA EDUCATION DELIVERY.
        /// </summary>
        public static string App_ApplicationTitle {
            get {
                return ResourceManager.GetString("App_ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string App_DefaultMOTD {
            get {
                return ResourceManager.GetString("App_DefaultMOTD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string App_HelpButtonContent {
            get {
                return ResourceManager.GetString("App_HelpButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No help available for this screen.
        /// </summary>
        public static string App_OpeningHelpErrorUnknowScreen {
            get {
                return ResourceManager.GetString("App_OpeningHelpErrorUnknowScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories: {0}.
        /// </summary>
        public static string CatalogueModelItem_CategoriesCount {
            get {
                return ResourceManager.GetString("CatalogueModelItem_CategoriesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string CataloguePage_DeleteButton {
            get {
                return ResourceManager.GetString("CataloguePage_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download all.
        /// </summary>
        public static string CataloguePage_DownloadAllButton {
            get {
                return ResourceManager.GetString("CataloguePage_DownloadAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string CataloguePage_HomeButton {
            get {
                return ResourceManager.GetString("CataloguePage_HomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string CataloguePage_RefreshButton {
            get {
                return ResourceManager.GetString("CataloguePage_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string CataloguePage_SearchButton {
            get {
                return ResourceManager.GetString("CataloguePage_SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media items enqueued for download: {0}.
        /// </summary>
        public static string CategoryModelItem_ItemsForDownload {
            get {
                return ResourceManager.GetString("CategoryModelItem_ItemsForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media items: {0} (downloaded: {1}, on server: {2} ).
        /// </summary>
        public static string CategoryModelItem_MediaItems {
            get {
                return ResourceManager.GetString("CategoryModelItem_MediaItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added to download queue.
        /// </summary>
        public static string DownloadCommand_AddedToDownload {
            get {
                return ResourceManager.GetString("DownloadCommand_AddedToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already downloaded.
        /// </summary>
        public static string DownloadCommand_AlreadyDownloaded {
            get {
                return ResourceManager.GetString("DownloadCommand_AlreadyDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} downloading started.
        /// </summary>
        public static string DownloadCommand_DownloadingStarted {
            get {
                return ResourceManager.GetString("DownloadCommand_DownloadingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string DownloadCommand_Item {
            get {
                return ResourceManager.GetString("DownloadCommand_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string DownloadListItemControl_CancelButton {
            get {
                return ResourceManager.GetString("DownloadListItemControl_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect with server. Make sure your network connection is working and try again..
        /// </summary>
        public static string Error_Connection {
            get {
                return ResourceManager.GetString("Error_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password cannot be empty.
        /// </summary>
        public static string Error_EmptyUsernameOrPassword {
            get {
                return ResourceManager.GetString("Error_EmptyUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("Error_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid NED server address.
        /// </summary>
        public static string Error_InvalidServerAddress {
            get {
                return ResourceManager.GetString("Error_InvalidServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library is already added.
        /// </summary>
        public static string Error_LibraryAlreadyAdded {
            get {
                return ResourceManager.GetString("Error_LibraryAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library was deleted from server.
        /// </summary>
        public static string Error_LibraryDeletedFromServer {
            get {
                return ResourceManager.GetString("Error_LibraryDeletedFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library doesn&apos;t exist..
        /// </summary>
        public static string Error_LibraryDoesNotExist {
            get {
                return ResourceManager.GetString("Error_LibraryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library id cannot be empty..
        /// </summary>
        public static string Error_LibraryIdEmpty {
            get {
                return ResourceManager.GetString("Error_LibraryIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error has occured..
        /// </summary>
        public static string Error_Unexpected {
            get {
                return ResourceManager.GetString("Error_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help not available.
        /// </summary>
        public static string HelpPage_HelpNotAvailable {
            get {
                return ResourceManager.GetString("HelpPage_HelpNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string HelpPage_Title {
            get {
                return ResourceManager.GetString("HelpPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to remove unknown item type.
        /// </summary>
        public static string LibraryModel_RemovingUnknowTypeError {
            get {
                return ResourceManager.GetString("LibraryModel_RemovingUnknowTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library is no longer available.
        /// </summary>
        public static string LibraryUnavailableAfterFailedUpdate {
            get {
                return ResourceManager.GetString("LibraryUnavailableAfterFailedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No links are attached to this media item..
        /// </summary>
        public static string LinkPage_NoLinksInfo {
            get {
                return ResourceManager.GetString("LinkPage_NoLinksInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to links.
        /// </summary>
        public static string LinksPage_Title {
            get {
                return ResourceManager.GetString("LinksPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MainPage_AboutButtonText {
            get {
                return ResourceManager.GetString("MainPage_AboutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.{1}.
        /// </summary>
        public static string MainPage_AboutVersionInfo {
            get {
                return ResourceManager.GetString("MainPage_AboutVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string MainPage_Add {
            get {
                return ResourceManager.GetString("MainPage_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding library.
        /// </summary>
        public static string MainPage_AddingLibrary {
            get {
                return ResourceManager.GetString("MainPage_AddingLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogues: {0}.
        /// </summary>
        public static string MainPage_CataloguesCount {
            get {
                return ResourceManager.GetString("MainPage_CataloguesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check for updates.
        /// </summary>
        public static string MainPage_CheckForUpdates {
            get {
                return ResourceManager.GetString("MainPage_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will be closed..
        /// </summary>
        public static string MainPage_ClosingApplicationMessage {
            get {
                return ResourceManager.GetString("MainPage_ClosingApplicationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string MainPage_ClosingApplicationTitle {
            get {
                return ResourceManager.GetString("MainPage_ClosingApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string MainPage_Connecting {
            get {
                return ResourceManager.GetString("MainPage_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to server.
        /// </summary>
        public static string MainPage_ConnectingToServer {
            get {
                return ResourceManager.GetString("MainPage_ConnectingToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string MainPage_Delete {
            get {
                return ResourceManager.GetString("MainPage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library will be removed from the device..
        /// </summary>
        public static string MainPage_DeleteLibQuestionMessage {
            get {
                return ResourceManager.GetString("MainPage_DeleteLibQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string MainPage_DeleteLibQuestionTitile {
            get {
                return ResourceManager.GetString("MainPage_DeleteLibQuestionTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string MainPage_Downloading {
            get {
                return ResourceManager.GetString("MainPage_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading library.
        /// </summary>
        public static string MainPage_DownloadingLib {
            get {
                return ResourceManager.GetString("MainPage_DownloadingLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.
        /// </summary>
        public static string MainPage_Downloads {
            get {
                return ResourceManager.GetString("MainPage_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter NED server address.
        /// </summary>
        public static string MainPage_EnterServerAddress {
            get {
                return ResourceManager.GetString("MainPage_EnterServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to factory reset.
        /// </summary>
        public static string MainPage_FactoryResetMenuItemText {
            get {
                return ResourceManager.GetString("MainPage_FactoryResetMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to libraries.
        /// </summary>
        public static string MainPage_Libraries {
            get {
                return ResourceManager.GetString("MainPage_Libraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to library manager.
        /// </summary>
        public static string MainPage_LibraryManager {
            get {
                return ResourceManager.GetString("MainPage_LibraryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in.
        /// </summary>
        public static string MainPage_LoggingIn {
            get {
                return ResourceManager.GetString("MainPage_LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in.
        /// </summary>
        public static string MainPage_logIn {
            get {
                return ResourceManager.GetString("MainPage_logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New library ID.
        /// </summary>
        public static string MainPage_NewLibraryID {
            get {
                return ResourceManager.GetString("MainPage_NewLibraryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string MainPage_NewVersionAvailableHeader {
            get {
                return ResourceManager.GetString("MainPage_NewVersionAvailableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace current version of this library with new version? (NOTE: all downloaded media will be deleted).
        /// </summary>
        public static string MainPage_NewVersionAvailableMessage {
            get {
                return ResourceManager.GetString("MainPage_NewVersionAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No downloads pending.
        ///
        ///You can select media items to download while browsing the Library..
        /// </summary>
        public static string MainPage_NoDownloadPending {
            get {
                return ResourceManager.GetString("MainPage_NoDownloadPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No libraries to display. 
        ///
        ///Use Library Manager to download libraries and add them here..
        /// </summary>
        public static string MainPage_NoLibrariesToDisplay {
            get {
                return ResourceManager.GetString("MainPage_NoLibrariesToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No libraries to display.
        ///
        ///Type in the library ID and click &apos;Add&apos; to check if library is available..
        /// </summary>
        public static string MainPage_NoLibrariesToDisplayTypeID {
            get {
                return ResourceManager.GetString("MainPage_NoLibrariesToDisplayTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string MainPage_OK {
            get {
                return ResourceManager.GetString("MainPage_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string MainPage_Password {
            get {
                return ResourceManager.GetString("MainPage_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string MainPage_Paused {
            get {
                return ResourceManager.GetString("MainPage_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        public static string MainPage_Queued {
            get {
                return ResourceManager.GetString("MainPage_Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me!.
        /// </summary>
        public static string MainPage_RememberMe {
            get {
                return ResourceManager.GetString("MainPage_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server wizard.
        /// </summary>
        public static string MainPage_ServerWizard {
            get {
                return ResourceManager.GetString("MainPage_ServerWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string MainPage_SettingsButtonContent {
            get {
                return ResourceManager.GetString("MainPage_SettingsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Libraries.
        /// </summary>
        public static string MainPage_ShowLibraries {
            get {
                return ResourceManager.GetString("MainPage_ShowLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics.
        /// </summary>
        public static string MainPage_StatisticsButtonContent {
            get {
                return ResourceManager.GetString("MainPage_StatisticsButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update not necessary.
        /// </summary>
        public static string MainPage_UpdateNotNecessaryHeader {
            get {
                return ResourceManager.GetString("MainPage_UpdateNotNecessaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the current version of this library. Do you want to download it anyway? (NOTE: all downloaded media will be deleted).
        /// </summary>
        public static string MainPage_UpdateNotNecessaryMessage {
            get {
                return ResourceManager.GetString("MainPage_UpdateNotNecessaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user login.
        /// </summary>
        public static string MainPage_UserLogin {
            get {
                return ResourceManager.GetString("MainPage_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string MainPage_UserName {
            get {
                return ResourceManager.GetString("MainPage_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views: {0}.
        /// </summary>
        public static string MainPage_ViewsCount {
            get {
                return ResourceManager.GetString("MainPage_ViewsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to queue.
        /// </summary>
        public static string MediaItemControl_AddToQueue {
            get {
                return ResourceManager.GetString("MediaItemControl_AddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string MediaItemControl_DeleteButton {
            get {
                return ResourceManager.GetString("MediaItemControl_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download now.
        /// </summary>
        public static string MediaItemControl_DonwloadNowButton {
            get {
                return ResourceManager.GetString("MediaItemControl_DonwloadNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description available.
        /// </summary>
        public static string MediaItemsListModelItem_NoDescriptionAvailable {
            get {
                return ResourceManager.GetString("MediaItemsListModelItem_NoDescriptionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string MediaItemsViewPage_DescriptionButtonText {
            get {
                return ResourceManager.GetString("MediaItemsViewPage_DescriptionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to links.
        /// </summary>
        public static string MediaItemsViewPage_LinksButtonText {
            get {
                return ResourceManager.GetString("MediaItemsViewPage_LinksButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are really sorry but we are unable to open this media item..
        /// </summary>
        public static string MediaItemViewerPage_CanNotOpenItem {
            get {
                return ResourceManager.GetString("MediaItemViewerPage_CanNotOpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture.
        /// </summary>
        public static string MediaItemViewerPage_Title {
            get {
                return ResourceManager.GetString("MediaItemViewerPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are really sorry but we are unable to show you this document..
        /// </summary>
        public static string MediaItemViewerPage_UnableToOpenDocument {
            get {
                return ResourceManager.GetString("MediaItemViewerPage_UnableToOpenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating library.
        /// </summary>
        public static string ProgressOverlay_UpdatingLibrary {
            get {
                return ResourceManager.GetString("ProgressOverlay_UpdatingLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results to display.
        ///
        ///Enter a valid keyword and press search button..
        /// </summary>
        public static string SearchPage_NoResultsToDisplay {
            get {
                return ResourceManager.GetString("SearchPage_NoResultsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchPage_Title {
            get {
                return ResourceManager.GetString("SearchPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic downloads.
        /// </summary>
        public static string SettingsPage_AutomaticDownloads {
            get {
                return ResourceManager.GetString("SettingsPage_AutomaticDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic statistics upload.
        /// </summary>
        public static string SettingsPage_AutomaticStatisticsUpload {
            get {
                return ResourceManager.GetString("SettingsPage_AutomaticStatisticsUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing data.
        /// </summary>
        public static string SettingsPage_ClearingData {
            get {
                return ResourceManager.GetString("SettingsPage_ClearingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to factory reset.
        /// </summary>
        public static string SettingsPage_FactoryResetButtonContent {
            get {
                return ResourceManager.GetString("SettingsPage_FactoryResetButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data will be removed..
        /// </summary>
        public static string SettingsPage_FactoryResetInfoMessage {
            get {
                return ResourceManager.GetString("SettingsPage_FactoryResetInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string SettingsPage_InfoHeader {
            get {
                return ResourceManager.GetString("SettingsPage_InfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging out.
        /// </summary>
        public static string SettingsPage_LoggingOut {
            get {
                return ResourceManager.GetString("SettingsPage_LoggingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logout user.
        /// </summary>
        public static string SettingsPage_LogoutButtonContent {
            get {
                return ResourceManager.GetString("SettingsPage_LogoutButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user will be logged out..
        /// </summary>
        public static string SettingsPage_LogoutInfoMessage {
            get {
                return ResourceManager.GetString("SettingsPage_LogoutInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove user.
        /// </summary>
        public static string SettingsPage_RemoveUserButtonContent {
            get {
                return ResourceManager.GetString("SettingsPage_RemoveUserButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing user.
        /// </summary>
        public static string SettingsPage_RemovingUser {
            get {
                return ResourceManager.GetString("SettingsPage_RemovingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All user data will be removed..
        /// </summary>
        public static string SettingsPage_UsersRemovedInfoMessage {
            get {
                return ResourceManager.GetString("SettingsPage_UsersRemovedInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No media items opened since last statistics upload to server.
        ///
        ///Statistics are uploaded automatically when &apos;Automatic upload&apos; turned on in settings..
        /// </summary>
        public static string StatisticPage_NoMediaOpened {
            get {
                return ResourceManager.GetString("StatisticPage_NoMediaOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no statistics to upload.
        /// </summary>
        public static string StatisticPage_NoStatisticToUpload {
            get {
                return ResourceManager.GetString("StatisticPage_NoStatisticToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started uploading statistics to server.
        /// </summary>
        public static string StatisticPage_StartedUploading {
            get {
                return ResourceManager.GetString("StatisticPage_StartedUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statistics.
        /// </summary>
        public static string StatisticPage_Title {
            get {
                return ResourceManager.GetString("StatisticPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string StatisticPage_UploadButton {
            get {
                return ResourceManager.GetString("StatisticPage_UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload statistics.
        /// </summary>
        public static string StatisticPage_UploadFiles {
            get {
                return ResourceManager.GetString("StatisticPage_UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics uploaded successfully.
        /// </summary>
        public static string StatisticPage_UploadingSucces {
            get {
                return ResourceManager.GetString("StatisticPage_UploadingSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleSwitch_OFF {
            get {
                return ResourceManager.GetString("ToggleSwitch_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleSwitch_ON {
            get {
                return ResourceManager.GetString("ToggleSwitch_ON", resourceCulture);
            }
        }
    }
}
